# Generated by Django 5.2.7 on 2025-10-06 18:16

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthlog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('steps', models.PositiveIntegerField(default=0)),
                ('distance_km', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('active_minutes', models.PositiveIntegerField(default=0)),
                ('exercise_type', models.CharField(blank=True, default='', max_length=100)),
                ('exercise_duration_min', models.PositiveIntegerField(default=0)),
                ('floors', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='HabitLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('water_ml', models.PositiveIntegerField(default=0)),
                ('caffeine_servings', models.PositiveIntegerField(default=0)),
                ('alcohol_servings', models.PositiveIntegerField(default=0)),
                ('medication_and_supplements', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='MoodLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('mood_score', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('stress_level', models.CharField(choices=[('low', 'Low'), ('med', 'Medium'), ('high', 'High')], default='med', max_length=5)),
                ('energy_level', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('notes', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='SleepLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_hours', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('quality', models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('bedtime', models.DateTimeField(default=django.utils.timezone.now)),
                ('wake_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='SymptomLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('headache_intensity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('pain_location', models.CharField(blank=True, default='', max_length=100)),
                ('pain_level', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('digestion_notes', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='VitalLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('resting_hr', models.PositiveIntegerField(default=0, help_text='beats per minute')),
                ('systolic', models.PositiveIntegerField(default=0)),
                ('diastolic', models.PositiveIntegerField(default=0)),
                ('temperature_c', models.FloatField(default=36.5, validators=[django.core.validators.MinValueValidator(30.0), django.core.validators.MaxValueValidator(45.0)])),
            ],
        ),
        migrations.CreateModel(
            name='WellbeingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('mindfulness_minutes', models.PositiveIntegerField(default=0)),
                ('time_outdoors_minutes', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='doctornote',
            name='author',
        ),
        migrations.RemoveField(
            model_name='doctornote',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='doctornote',
            name='user',
        ),
        migrations.RemoveField(
            model_name='glucoseentry',
            name='note',
        ),
        migrations.RemoveField(
            model_name='glucoseentry',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='glucoseentry',
            name='user',
        ),
        migrations.RemoveField(
            model_name='medicationentry',
            name='medication_name',
        ),
        migrations.RemoveField(
            model_name='medicationentry',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='medicationentry',
            name='recorded_at',
        ),
        migrations.RemoveField(
            model_name='medicationentry',
            name='taken_at',
        ),
        migrations.RemoveField(
            model_name='medicationentry',
            name='user',
        ),
        migrations.RemoveField(
            model_name='nutritionentry',
            name='fats_g',
        ),
        migrations.RemoveField(
            model_name='nutritionentry',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='nutritionentry',
            name='user',
        ),
        migrations.AddField(
            model_name='glucoseentry',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='medicationentry',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='medicationentry',
            name='drug_name',
            field=models.CharField(blank=True, default='Unknown', max_length=120),
        ),
        migrations.AddField(
            model_name='medicationentry',
            name='time_taken',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='nutritionentry',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='nutritionentry',
            name='fat_g',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='doctornote',
            name='content',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='doctornote',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='glucoseentry',
            name='glucose_mg_dl',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='medicationentry',
            name='dosage',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='nutritionentry',
            name='calories',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='nutritionentry',
            name='carbs_g',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='nutritionentry',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='nutritionentry',
            name='protein_g',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
