# Generated by Django 5.2.6 on 2025-11-07 17:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DismissedHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('high_glucose', 'High Glucose'), ('low_sleep', 'Low Sleep'), ('activity_drop', 'Activity Drop')], max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hidden_until', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'key', 'hidden_until'], name='analytics_d_user_id_413051_idx')],
            },
        ),
    ]
