# Generated by Django 5.2.6 on 2025-10-16 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('data_sharing_consent', models.BooleanField(default=False, verbose_name='Consent to share anonymized health data for research/insurance purposes.')),
                ('consent_timestamp', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
