# Generated by Django 5.2.6 on 2025-10-22 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0003_provideralert'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
        migrations.AlterModelOptions(
            name='provideralert',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='profile',
            name='consent_timestamp',
            field=models.DateTimeField(blank=True, help_text='When the user last updated their consent preference', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='data_sharing_consent',
            field=models.BooleanField(default=False, verbose_name='Consent to share anonymized health data for research/insurance purposes'),
        ),
    ]
