# Generated by Django 5.2.6 on 2025-10-22 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0004_delete_customuser_alter_provideralert_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='activity_level',
            field=models.CharField(choices=[('sedentary', 'Sedentary - Little or no exercise'), ('light', 'Lightly Active - Light exercise 1-3 days/week'), ('moderate', 'Moderately Active - Moderate exercise 3-5 days/week'), ('active', 'Active - Hard exercise 6-7 days/week'), ('very_active', 'Very Active - Very hard exercise & physical job')], default='sedentary', help_text='Your typical weekly activity level', max_length=20),
        ),
    ]
