# Generated by Django 5.2.6 on 2025-10-03 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthdata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(max_length=100)),
                ('steps', models.IntegerField()),
                ('calories_burned', models.IntegerField()),
                ('heart_rate', models.IntegerField(blank=True, null=True)),
                ('sleep_minutes', models.IntegerField(blank=True, null=True)),
                ('recorded_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='HealthPrivacySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_steps', models.BooleanField(default=False)),
                ('share_heart_rate', models.BooleanField(default=False)),
                ('share_sleep_data', models.BooleanField(default=False)),
                ('share_calories', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='healthconsent',
            name='user',
        ),
    ]
