# Generated by Django 5.2.6 on 2025-10-22 20:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthdata', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_type', models.CharField(choices=[('nutrition', 'Nutrition'), ('activity', 'Activity'), ('hydration', 'Hydration'), ('sleep', 'Sleep'), ('general', 'General')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField(help_text='Short message (1-2 sentences)')),
                ('explanation', models.TextField(help_text='Detailed explanation of WHY this matters')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('actionable_steps', models.JSONField(default=list, help_text='List of specific actions user can take')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dismissed_at', models.DateTimeField(blank=True, null=True)),
                ('acted_upon', models.BooleanField(default=False)),
                ('acted_upon_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_reminders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'dismissed_at'], name='healthdata__user_id_44c839_idx')],
            },
        ),
    ]
