# Generated by Django 5.2.7 on 2025-10-24 05:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthdata', '0002_healthreminder'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logged_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('heart_rate_resting', models.PositiveIntegerField(blank=True, null=True)),
                ('blood_pressure_systolic', models.PositiveIntegerField(blank=True, null=True)),
                ('blood_pressure_diastolic', models.PositiveIntegerField(blank=True, null=True)),
                ('blood_oxygen', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('body_fat_percentage', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('muscle_mass_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('stress_level', models.PositiveIntegerField(blank=True, help_text='0-100 scale', null=True)),
                ('hrv', models.PositiveIntegerField(blank=True, help_text='Heart Rate Variability', null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_metrics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-logged_at'],
            },
        ),
        migrations.CreateModel(
            name='ActivityData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('activity_type', models.CharField(choices=[('walking', 'Walking'), ('running', 'Running'), ('cycling', 'Cycling'), ('swimming', 'Swimming'), ('workout', 'Workout'), ('general', 'General')], default='general', max_length=20)),
                ('steps', models.PositiveIntegerField(default=0)),
                ('distance_km', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('active_minutes', models.PositiveIntegerField(default=0)),
                ('calories_burned', models.PositiveIntegerField(default=0)),
                ('heart_rate_avg', models.PositiveIntegerField(blank=True, null=True)),
                ('heart_rate_max', models.PositiveIntegerField(blank=True, null=True)),
                ('floors_climbed', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_data', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
                'unique_together': {('user', 'date', 'activity_type')},
            },
        ),
        migrations.CreateModel(
            name='SleepData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('total_sleep_minutes', models.PositiveIntegerField()),
                ('deep_sleep_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('light_sleep_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('rem_sleep_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('awake_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('sleep_quality', models.CharField(blank=True, choices=[('poor', 'Poor'), ('fair', 'Fair'), ('good', 'Good'), ('excellent', 'Excellent')], max_length=10, null=True)),
                ('sleep_score', models.PositiveIntegerField(blank=True, null=True)),
                ('times_awake', models.PositiveIntegerField(default=0)),
                ('bedtime_start', models.DateTimeField(blank=True, null=True)),
                ('bedtime_end', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sleep_data', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
