# Generated by Django 5.2.6 on 2025-11-09 07:48

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthdata', '0004_doctornote_glucoseentry_medicationentry_moodlog_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_type', models.CharField(choices=[('steps', 'Steps'), ('distance_km', 'Distance (km)'), ('active_min', 'Active minutes'), ('calories', 'Calories burned'), ('weight', 'Weight'), ('water_l', 'Water (L)'), ('protein_g', 'Protein (g)'), ('carbs_g', 'Carbs (g)'), ('fat_g', 'Fat (g)')], max_length=32)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('one_off', 'One-off')], default='daily', max_length=16)),
                ('target_value', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('current_value', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('start_date', models.DateField(default=django.utils.timezone.localdate)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('expired', 'Expired')], default='active', max_length=16)),
                ('title', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='GoalProgressLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_on', models.DateField(default=django.utils.timezone.localdate)),
                ('delta_value', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('source', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='healthdata.goal')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['applied_on'], name='healthdata__applied_00ceb0_idx')],
            },
        ),
    ]
