# Generated by Django 5.2.6 on 2025-11-09 08:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthdata', '0005_goal_goalprogresslog'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='progress',
            field=models.FloatField(default=0.0, help_text='Percentage of progress toward goal'),
        ),
        migrations.AlterField(
            model_name='habitlog',
            name='alcohol_servings',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='habitlog',
            name='caffeine_servings',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='habitlog',
            name='medication_and_supplements',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='habitlog',
            name='water_ml',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='moodlog',
            name='energy_level',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='moodlog',
            name='mood_score',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='symptomlog',
            name='headache_intensity',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='symptomlog',
            name='pain_level',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='vitallog',
            name='diastolic',
            field=models.PositiveIntegerField(default=0, help_text='Diastolic BP'),
        ),
        migrations.AlterField(
            model_name='vitallog',
            name='resting_hr',
            field=models.PositiveIntegerField(default=0, help_text='Resting heart rate (BPM)'),
        ),
        migrations.AlterField(
            model_name='vitallog',
            name='systolic',
            field=models.PositiveIntegerField(default=0, help_text='Systolic BP'),
        ),
        migrations.AlterField(
            model_name='vitallog',
            name='temperature_c',
            field=models.FloatField(default=36.5, validators=[django.core.validators.MinValueValidator(30.0), django.core.validators.MaxValueValidator(45.0)]),
        ),
        migrations.AlterField(
            model_name='wellbeinglog',
            name='mindfulness_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wellbeinglog',
            name='time_outdoors_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
